- name: /etc/gshadow
  file:
    path: /etc/gshadow
    owner: root  # TWGCB-01-008-0051,TWGCB-01-003-0032
    group: root  # TWGCB-01-008-0051,TWGCB-01-003-0033
    mode: 0000 # TWGCB-01-008-0052,TWGCB-01-003-0031

- name: /etc/shadow
  file:
    path: /etc/shadow
    owner: root  # TWGCB-01-008-0047,TWGCB-01-003-0035
    group: root  # TWGCB-01-008-0047,TWGCB-01-003-0036
    mode: '0000' # TWGCB-01-008-0048,TWGCB-01-003-0034

- name: /etc/group
  file:
    path: /etc/group
    owner: root  # TWGCB-01-008-0049,TWGCB-01-003-0038
    group: root  # TWGCB-01-008-0049,TWGCB-01-003-0039
    mode: '0644' # TWGCB-01-008-0050,TWGCB-01-003-0037

- name: /etc/passwd
  file:
    path: /etc/passwd
    owner: root  # TWGCB-01-008-0045,TWGCB-01-003-0041
    group: root  # TWGCB-01-008-0045,TWGCB-01-003-0042
    mode: '0644' # TWGCB-01-008-0046,TWGCB-01-003-0040

- name: /etc/passwd-
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version | int >= 8
  file:
    path: /etc/passwd-
    owner: root  # TWGCB-01-008-0053
    group: root  # TWGCB-01-008-0053
    mode: '0000' # TWGCB-01-008-0054