
- name: Debian Base version
  when: ansible_distribution == "Debian"
  block:
  - name: TWGCB-install-package
    apt:
      name: "{{ item }}"
    with_items:
      "{{ install_package }}"

- name: RedHat Base version
  when: ansible_distribution == "RedHat"
  block:
  - name: TWGCB-install-package
    yum:
      name: "{{ item }}"
    with_items:
      "{{ install_package }}"

- name: RedHat Base version 6
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "6"
  block:
  - name: TWGCB-01-003-0006(安裝Red Hat GPG金鑰)
  shell: |
    #!/bin/bash
    curl https://access.redhat.com/security/data/fd431d51.txt >> /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
    rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
#   - name: TWGCB-install-package
#     yum:
#       name: "{{ item }}"
#     with_items:
#       "{{ install_package }}"
    
# - name: RedHat Base version 7
#   when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "6"
#   block:
#   - name: TWGCB-install-package
#     yum:
#       name: "{{ item }}"
#     with_items:
#       "{{ install_package }}"
    

- name: RedHat Base version 5 6 7
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version in ["5","6","7"]
  block:
  - name: TWGCB-install-package-TWGCB-01-003
    yum:
      name: "{{ item }}"
    with_items:
      "{{ install_package_TWGCB_01_003 }}"
    

- name: RedHat Base version is no less than 8
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version | int >= 8
  block:
  - name: TWGCB-install-package-TWGCB-01-008
    dnf:
      name: "{{ item }}"
    with_items:
      "{{ install_package_TWGCB_01_008 }}"

