---
- name: TWGCB-01-008-0126 push /etc/modprobe.d/dccp.conf
  become: true
  copy:
    src: files/{{ansible_distribution}}/{{ansible_distribution_major_version}}/etc/modprobe.d/dccp.conf
    dest: /etc/modprobe.d
    owner: root
    group: root
    mode: 0644
