---
- name: TWGCB-base-check-disable CentOS-6
  ignore_errors: true
  become: true
  service:
    enabled: no
    state: stopped
    name: "{{ item }}"
  with_items:
    "{{ disable_packages }}"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

- name: TWGCB-base-check-disable CentOS-7
  ignore_errors: true
  become: true
  systemd:
    enabled: no
    state: stopped
    name: "{{ item }}"
  with_items:
    "{{ disable_packages }}"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: TWGCB-base-check-disable OracleLinux-9
  ignore_errors: true
  become: true
  systemd:
    enabled: no
    state: stopped
    name: "{{ item }}"
  with_items:
    "{{ disable_packages }}"
  when: ansible_distribution == "OracleLinux" and ansible_distribution_major_version == "9"

