---
- name: TWGCB-01-008-0031 push /etc/modprobe.d/usb-storage.conf
  become: true
  copy:
    src: files/{{ansible_distribution}}/{{ansible_distribution_major_version}}/etc/modprobe.d/usb-storage.conf
    dest: /etc/modprobe.d
    owner: root
    group: root
    mode: 0644

- name: TWGCB-01-008-0031 command
  ignore_errors: true
  become: true
  command: rmmod usb-storage