# 排程處理項目

- name: TWGCB-01-008-0139,TWGCB-01-008-0142 /etc/audit/auditd.conf
  become: true
  file:
    path: /etc/audit/auditd.conf
    owner: root  # TWGCB-01-008-0139
    group: root  # TWGCB-01-008-0139
    mode: '0640' # TWGCB-01-008-0142

- name: TWGCB-01-008-0141 /etc/audit/rules.d/audit.rules
  become: true
  file:
    path: /etc/audit/rules.d/audit.rules
    owner: root
    group: root
    mode: '0600' # TWGCB-01-008-0141

- name: TWGCB-01-008-0178 /var/log/messages
  become: true
  file:
    path: /var/log/messages
    owner: root
    group: root

- name: TWGCB-01-008-0179 /var/log
  become: true
  file:
    path: /var/log
    owner: root
    group: root

- name: TWGCB-01-008-0193,TWGCB-01-008-0194 /etc/crontab
  become: true
  file:
    path: /etc/crontab
    owner: root # TWGCB-01-008-0193
    group: root # TWGCB-01-008-0193
    mode: '0600' # TWGCB-01-008-0194

- name: TWGCB-01-008-0195,TWGCB-01-008-0196 /etc/cron.hourly
  become: true
  file:
    path: /etc/cron.hourly
    owner: root # TWGCB-01-008-0195
    group: root # TWGCB-01-008-0195
    mode: '0700' # TWGCB-01-008-0196

- name: TWGCB-01-008-0197,TWGCB-01-008-0198 /etc/cron.daily
  become: true
  file:
    path: /etc/cron.daily
    owner: root # TWGCB-01-008-0197
    group: root # TWGCB-01-008-0197
    mode: '0700' # TWGCB-01-008-0198

- name: TWGCB-01-008-0199,TWGCB-01-008-0200 /etc/cron.weekly
  become: true
  file:
    path: /etc/cron.weekly
    owner: root # TWGCB-01-008-0199
    group: root # TWGCB-01-008-0199
    mode: '0700' # TWGCB-01-008-0200

- name: TWGCB-01-008-0201,TWGCB-01-008-0202 /etc/cron.monthly
  become: true
  file:
    path: /etc/cron.monthly
    owner: root # TWGCB-01-008-0201
    group: root # TWGCB-01-008-0201
    mode: '0700' # TWGCB-01-008-0202

- name: TWGCB-01-008-0203,TWGCB-01-008-0204 /etc/cron.d
  become: true
  file:
    path: /etc/cron.d
    owner: root # TWGCB-01-008-0203
    group: root # TWGCB-01-008-0203
    mode: '0700' # TWGCB-01-008-0204
