- name: TWGCB-01-008-0029 command
  ignore_errors: true
  become: true
  shell: df --local -P | awk '{if (NR!=1) print $6}' | xargs -I '{}' find '{}' -xdev -type d \( -perm -0002 -a ! -perm -1000 \) 2>/dev/null | xargs -I '{}' chmod o+t '{}'
  args:
    executable: /bin/bash