- name: TWGCB-audit push /etc/rsyslog.conf
  become: true
  copy:
    src: files/{{ansible_distribution}}/{{ansible_distribution_major_version}}/etc/rsyslog.conf
    dest: /etc
    owner: root
    group: root
    mode: 0644

- name: TWGCB-audit push /etc/systemd/journald.conf
  become: true
  copy:
    src: files/{{ansible_distribution}}/{{ansible_distribution_major_version}}/etc/systemd/journald.conf
    dest: /etc/systemd
    owner: root
    group: root
    mode: 0644

- name: restart rsyslog with systemd
  become: true
  systemd:
    enabled: yes # TWGCB-01-008-0177
    state: restarted
    name: rsyslog