---
- name: TWGCB-01-008-0003 push /etc/modprobe.d/udf.conf
  become: true
  copy:
    src: files/{{ansible_distribution}}/{{ansible_distribution_major_version}}/etc/modprobe.d/udf.conf
    dest: /etc/modprobe.d
    owner: root
    group: root
    mode: 0644

- name: TWGCB-01-008-0003 command
  ignore_errors: true
  become: true
  command: rmmod udf