- name: TWGCB-selinux push /etc/selinux/config
  become: true
  copy:
    src: files/{{ansible_distribution}}/{{ansible_distribution_major_version}}/etc/selinux/config
    dest: /etc/selinux
    owner: root
    group: root
    mode: 0640

- name: TWGCB-01-008-0186
  become: true
  ignore_errors: true
  command: grub2-mkconfig -o /boot/grub2/grub.cfg
